# Generated by Django 5.2.3 on 2025-07-02 16:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(default='Cuenca', max_length=100)),
                ('num_habitantes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='core.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('puntos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('tipo_usuario', models.CharField(choices=[('ciudadano', 'Ciudadano'), ('lider', 'Líder'), ('organizacion', 'Organización')], max_length=20)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Cédula debe tener 10 dígitos numéricos')])),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Número de teléfono inválido')])),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='ReconocimientoResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_residuo', models.CharField(max_length=100)),
                ('porcentaje_confianza', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('imagen', models.URLField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residuos_reconocidos', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen_url', models.URLField(blank=True)),
                ('actualizados_en', models.DateField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.URLField()),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('otro', 'Otro')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateField(default=django.utils.timezone.now)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoBarrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_actualizacion', models.DateField(default=django.utils.timezone.now)),
                ('progreso', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='core.barrio')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='core.proyecto')),
            ],
            options={
                'unique_together': {('proyecto', 'barrio')},
            },
        ),
        migrations.CreateModel(
            name='ProyectoBarrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asociados', to='core.barrio')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios_asociados', to='core.proyecto')),
            ],
            options={
                'unique_together': {('barrio', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='LiderProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lideres', to='core.proyecto')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liderazgos', to='core.usuario')),
            ],
            options={
                'unique_together': {('lider', 'proyecto')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioInsignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateField(default=django.utils.timezone.now)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to='core.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'insignia')},
            },
        ),
    ]
