# Generated by Django 5.2.4 on 2025-07-08 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='proyectobarrio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proyectobarrio',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='proyectobarrio',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='evidenciaactividad',
            name='es_valida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidenciaactividad',
            name='fecha_validacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenciaactividad',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_validadas', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='representante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='ruc',
            field=models.CharField(default='0000000000000', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'El RUC debe tener 13 dígitos')]),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='progreso',
            field=models.CharField(choices=[('por_iniciar', 'Por iniciar'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado')], default='por_iniciar', max_length=20),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LiderProyectoBarrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lideres_proyecto', to='core.barrio')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lideres_barrio', to='core.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liderazgos_barrio', to='core.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'proyecto', 'barrio')},
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='core.ciudad')),
            ],
            options={
                'unique_together': {('nombre', 'ciudad')},
            },
        ),
        migrations.AddField(
            model_name='barrio',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='core.parroquia'),
        ),
        migrations.AlterUniqueTogether(
            name='barrio',
            unique_together={('nombre', 'parroquia')},
        ),
        migrations.DeleteModel(
            name='LiderProyecto',
        ),
        migrations.DeleteModel(
            name='ProyectoBarrio',
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='ciudad',
        ),
    ]
