from .barrio import Barrio
from .usuario import Usuario
from .noticia import Noticia
from .organizacion import Organizacion
from .proyecto import Proyecto
from .actividad import Actividad
from .evidencia import EvidenciaActividad
from .lider_proyecto_barrio import LiderProyectoBarrio
from .reconocimiento import ReconocimientoResiduo
from .insignia import Insignia
from .usuario_insignia import UsuarioInsignia
from .ciudad import Ciudad
from .parroquia import Parroquia
from .progreso_barrio import ProgresoBarrio
from .usuario_proyecto import UsuarioProyecto